- config.toml
- sass/main.scss
- sass/syntax/syntax-ayu-dark.scss
This Pull Requests fixes the syntax highlighting by using the css styles instead of the theme from zola.
> :bug: fix: syntax highlighting

- README.md
- theme.toml
The idea is to host in github pages with automatic updates, but this will do for now.
> 📝 fix: working live url

- sass/parts/_cards.scss
- sass/parts/_code.scss
- sass/parts/_header.scss
- sass/parts/_home-banner.scss
- sass/parts/_misc.scss
- sass/parts/_theme-switch.scss
Only border radius left is main picture.
> 💄style: set consistent no border radius

- content/_index.md
Otherwise it would fail to load when changing page.
> 🐛 fix: set absolute path to main image

- sass/main.scss
- sass/parts/_code.scss
- sass/parts/_header.scss
- sass/parts/_home-banner.scss
- sass/parts/_misc.scss
- templates/macros/macros.html
The narrower width for the articles makes them more readable.
> 💄 style: narrower blog layout, smaller and thinner text, and more

- sass/main.scss
- sass/parts/_footer.scss
- sass/parts/_home-banner.scss
Social icons were too big on smaller screens.
Fix #34
> 📱 feat: make footer & banner responsive

- templates/base.html
- templates/macros/set_title.html
- templates/partials/header.html
> 🐛 fix: use set_title macro to set proper titles

- README.md
- content/shortcodes.md
- sass/parts/_misc.scss
- templates/shortcodes/references.html
Uses hanging indent for a References section.
> ✨ feat: format references with custom shortcode

- content/blog/toc.ca.md
- content/blog/toc.es.md
- content/blog/toc.md
- templates/base.html
- templates/macros/content.html
- templates/macros/table_of_contents.html
- templates/shortcodes/toc.html
<details>
<summary>TL;DR</summary>
- Added the `toc_ignore_pattern` option to skip specific headers using regex.
- Enabled custom ToC placement via a shortcode or `` marker.
- Extended max ToC depth to 4.
- Updated associated documentation and refactored ToC generation.
</details>
This pull request brings several enhancements to the Table of Contents (ToC), increasing its flexibility and usability.
- **`toc_ignore_pattern`**: Introduced a new front matter variable that allows users to specify headers they wish to ignore in the ToC based on regex patterns. This can help reduce clutter in articles with many repetitive headers (e.g., multiple figures or tables).
- Custom ToC Placement: Users now have the flexibility to place the ToC wherever they want in their content using a shortcode or …
> ✨ feat: overhaul Table of Contents

- templates/partials/header.html
- templates/partials/multilingual_tags.html
This PR improves the meta tags to improve SEO and accessibility.
- **Open graph title**: Use the page title, if available, for the Open Graph `og:title` property. Resolves #148.
- **Improved multilingual support**: Included locale and hreflang tags for multilingual support.
- **Image Metadata**: Introduced Open Graph image width and height metadata.
- **Conditional Open Graph URL**: Made the `og:url` tag conditional based on whether `current_url` exists (so it doesn't get added for the 404 page).
> 🔍️ feat: enhance SEO and accessibility with meta tags

- templates/atom.xml
Small change so I decided to make a PR instead of an issue
> 🐛 fix(i18n): use English by default in atom.xml

- README.md
Added mikufan.page into the Sites using Tabi section in the README
> Add mikufan.page to Sites using Tabi section in README

- sass/parts/_posts_list.scss
- templates/macros/list_posts.html
Closes https://github.com/welpo/tabi/issues/202, surfacing the draft status.
@welpo I'm bad at CSS, so don't hesitate to push changes directly to the branch.
> ✨ feat(list_posts.html): display draft status in post list

- sass/main.scss
Fixes https://github.com/welpo/tabi/issues/209, screenshots below using the repo case from the issue:
> 💄 fix(style): proper nested lists spacing

- README.md
> Update README.md - added to sites using tabi

- sass/parts/_header-anchor.scss
Fix https://github.com/welpo/tabi/issues/269
Will looks like after this PR
https://github.com/welpo/tabi/assets/59842932/a20d76a5-901c-41fc-803d-15c55dfe800b
https://github.com/welpo/tabi/assets/59842932/be8fc595-cbc2-4ad6-b0eb-d93ed1c70bbc
> 🐛 fix(i18n): fix header anchor in arabic

- sass/parts/_cards.scss
Adds corner radius, changes shadow and aligns text to center for projects (cards template).
Old design:
New:
Open to feedback!
> 💄 style(projects): minor redesign

- i18n/fr.toml
I have corrected and improved certain suggestions in the French (FR) translation file.
---
> 🌐 fix(i18n): improve FR translations and correct typos

- content/blog/shortcodes/index.ca.md
- content/blog/shortcodes/index.es.md
- content/blog/shortcodes/index.md
- sass/main.scss
- sass/parts/_admonitions.scss
- templates/shortcodes/admonition.html
Adds "admonition" shortcode, inspired by [Docusaurus](https://docusaurus.io/docs/next/markdown-features/admonitions).
Using them is as simple as:
```
{{ admonition(type="note", title="Custom title", text="Some **content** with _Markdown_ `syntax`. Check [this `api`](#).") }}
```
Docs available in the [shortcodes page](https://welpo.github.io/tabi/blog/shortcodes/#admonitions).
---
> ✨ feat(shortcodes): add admonition shortcodes

- templates/partials/history_url.html
Fixes: https://github.com/welpo/tabi/issues/293
---
> 🐛 fix: fix history url for GitLab & Codeberg

- templates/macros/list_posts.html
- templates/section.html
Fix the "All posts" link, which used to be hard-coded to link to the section "blog", which may not actually exist or not be the desired target of this link.
#292
Changes were made to two templates: 
- `macros/list_posts` : this is the incriminated macro, that had a hardcoded "blog" string; this was left as a default value when adding a new parameter to fix the issue, although that default parameter should in principle never be actually used
- `section` : the call to the previous macro is changed to reflect the current section's path
- note that 3 other files where found that call the `list_posts` macro, but experimentation shows that they are not involved in the bug we're trying to fix, as no "All posts" link is generated by their calls to `list_posts`; they therefore do not need to …
> 🐛 fix: link 'All posts' to proper section

- README.md
Added my website to the "using tabi" section
None
Only README.md
No changes to website or CSS etc.
---
> 📝 docs(README): add arichtman blog to showcase

- content/blog/shortcodes/index.ca.md
- content/blog/shortcodes/index.es.md
- content/blog/shortcodes/index.md
- templates/shortcodes/remote_text.html
Adds the shortcode `remote_text` to allow embedding content from URLs or local files.
Resolves #304.
- Introduced a new shortcode `remote_text` that supports both remote URLs and local file paths.
- The shortcode automatically differentiates between remote and local sources based on the prefix of the `src` attribute.
For example, to embed a remote Python script within a code block with syntax highlighting:
````
```python
{{/* remote_text(src="https://example.com/script.py") */}}
```
````
See [the docs](https://welpo.github.io/tabi/blog/shortcodes/#remote-text) for more information.
---
> ✨ feat(shortcodes): add remote_text shortcode

- content/blog/faq-languages/index.ca.md
- content/blog/faq-languages/index.es.md
- content/blog/faq-languages/index.md
- i18n/or.toml
- [Odia Language](https://en.wikipedia.org/wiki/Odia_language) support added
- `or.toml` file added
Not Applicable
---
> 🌐 feat(i18n): add Odia language

- README.md
Thank you for all the help, @welpo! 😊 We're very happy with the new site.
> Add Ponderosa Games to "Sites using tabi"

- content/blog/shortcodes/index.ca.md
- content/blog/shortcodes/index.es.md
- content/blog/shortcodes/index.md
- templates/shortcodes/remote_text.html
Adds support for relative paths in `remote_text` shortcode.
Requested in #397.
---
> ✨ feat(remote_text shortcode): support relative paths

- README.md
Adds my personal website to the example list
Thank you for the theme. It's great!
> Adds jmbhughes.com to example list

- templates/partials/content_security_policy.html
This PR changes `connect-src` in the CSP for GoatCounter to include `[analytics.id].goatcounter.com/count` instead of `gc.zgo.at` ( see https://www.goatcounter.com/help/csp).
---
> 🐛 fix: update CSP for GoatCounter

- content/blog/shortcodes/index.ca.md
- content/blog/shortcodes/index.es.md
- content/blog/shortcodes/index.md
- templates/shortcodes/admonition.html
Add support for using admonition shortcodes with a content body:
```md
{% admonition(type="danger", icon="tip", title="An important tip") %}
Stay hydrated~
This method is particularly useful for longer content or multiple paragraphs.
{% end %}
```
This allows for more natural writing of longer content blocks while maintaining backward compatibility with the existing parameter-based syntax.
- Added support for body content in admonition shortcodes
- Updated documentation in all languages to show both usage methods
- Maintained backward compatibility with existing parameter-based syntax
---
> ✨ feat(shortcodes): support body admonitions

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- config.toml
- content/_index.ca.md
- content/_index.es.md
- content/_index.md
- content/blog/mastering-tabi-settings/index.ca.md
- content/blog/mastering-tabi-settings/index.es.md
- content/blog/mastering-tabi-settings/index.md
- theme.toml
Adds references to the [tabi-start template](https://github.com/welpo/tabi-start) for a quick setup. 
Also updates project description to reflect key features.
- Adds prominent tabi-start quick start option in README
- Restructures installation section to highlight tabi-start as recommended path
- Updates PR template to ensure tabi-start config stays in sync
- Updates project description across files to focus on accessibility and core features
- Fixes internal links in mastering-tabi-settings guide
---
> 📝 docs: add tabi-start integration

- templates/partials/analytics.html
- templates/partials/content_security_policy.html
- Update Umamai script source FQDN to their new one
- No related issue
- 
- Content security policy amended
- Partial for analytics amended
No visual elements impacted.
You can view the changes from this branch live at https://www.richtman.au with the source being https://github.com/arichtman/www.richtman.au/commit/559960917de82cd2c221116fd852ab7feea1192d
---
> 🐛 fix(analytics): update umami domain

- README.md
This commit adds szabolcs.me to the README.md in the "Sites using tabi" section.
---
> 📝 docs(README): add szabolcs.me to Sites using tabi

- README.md
> 📝 misc(README): add nizzlay.com to Sites using tabi

- templates/section.html
Text in a section is now rendered similarly to on the home page. Before, this content was ignored.
Example code:
```md
+++
title = "Notes"
sort_by = "date"
template = "section.html"
+++
Mostly notes for my future self. Always pruning, always growing.
```
The "Mostly notes…" part would not get rendered before. Now you get:
---
> ✨ feat: render section content

- content/blog/mastering-tabi-settings/index.ca.md
- content/blog/mastering-tabi-settings/index.es.md
- content/blog/mastering-tabi-settings/index.md
- templates/atom.xml
Add `hide_from_main_feed` setting to allow hiding content from the main feed while keeping it visible in section and tag feeds.
- Added `hide_from_main_feed` setting, a more granular version of `hide_from_feed` that only affects the main feed
- Updated documentation
- `hide_from_main_feed = true` will:
- Hide content from the main feed
- Keep content visible in section feeds
- Keep content visible in tag feeds
- Setting can be used at page, section, and config.toml level
No accessibility impact.
---
> ✨ feat: add `hide_from_main_feed` support

- sass/parts/_code.scss
This fixes the design of a code with link when hovering.
Before:
After:
---
> 🐛 fix: fix padding hover on links with code (custom font)

- README.md
Add my personal blog ([tzinm@blog:~$](https://tzinm.me)) to the [_Sites using tabi_](https://github.com/welpo/tabi?tab=readme-ov-file#sites-using-tabi) section of the README file.
> 📝 misc(README): add tzinm's blog to 'sites using tabi'

- content/blog/faq-languages/index.ca.md
- content/blog/faq-languages/index.es.md
- content/blog/faq-languages/index.md
- i18n/fi.toml
Added Finnish language support
Please see the comments near the following fields: `by_author`, `toggle_mode` and `pinned`.
---
> 🌐 feat(i18n): add Finnish language

- templates/shortcodes/dimmable_image.html
- templates/shortcodes/dual_theme_image.html
- templates/shortcodes/full_width_image.html
- templates/shortcodes/image_hover.html
- templates/shortcodes/image_toggler.html
- templates/shortcodes/invertible_image.html
Forces cache busting in image shortcodes.
Brief discussion in #503
---
> ✨ feat: cache bust images in shortcodes

- README.md
> 📝 misc(README): fix broken link tag

- README.md
Add my blog to showcase.
GREAT theme.
> 📝 misc(README): add b1n.io to 'sites using tabi'

- config.toml
- content/blog/mastering-tabi-settings/index.ca.md
- content/blog/mastering-tabi-settings/index.es.md
- content/blog/mastering-tabi-settings/index.md
- templates/base.html
- templates/partials/header.html
This pull request adds optional includes to the end of the `<head>` and `<body>` elements in Tabi. Users can provide these templates in their repositories to add additional content to the respective elements.
See #526 for related discussion.
Only the template files have added `include` statements for optional templates. So, users can provide these without needing to supply additional configuration.
---
> ✨ feat: extend tabi `<head>` and `<body>` elements

- i18n/ar.toml
Fix iine Arabic translation
i18n
---
> 🌐 fix(i18n): iine Arabic translation

- i18n/ar.toml
- i18n/ca.toml
- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/et.toml
- i18n/fa.toml
- i18n/fi.toml
- i18n/fr.toml
- i18n/hi.toml
- i18n/it.toml
- i18n/ja.toml
- i18n/ko.toml
- i18n/nl.toml
- i18n/or.toml
- i18n/pt-PT.toml
- i18n/ru.toml
- i18n/uk.toml
- i18n/zh-Hans.toml
- i18n/zh-Hant.toml
- sass/parts/_misc.scss
- templates/base.html
Adds a "Skip to content" link to improve keyboard navigation accessibility. The skip link allows keyboard users, screen reader users, and users with motor disabilities to bypass navigation elements and jump directly to the main content area.
- **HTML**: Add skip link as first focusable element targeting `#main-content`
- **CSS**: Hidden by default, visible on focus with high-contrast outline
- **i18n**: Add `skip_to_content` translation key
- **Semantic HTML**: Uses proper anchor element with meaningful href target
- **ARIA compliance**: Leverages existing internationalization system for screen reader compatibility
- **Keyboard navigation**: First tab stop provides immediate access to main content
- **Screen reader compatibility**: Uses translated text appropriate for each language
- …
> ♿️ feat(a11y): add skip to content link for keyboard navigation
