sass/syntax/syntax-ayu-dark.scss
Lowers the contrast for codeblocks' background in light theme and increases it for the dark theme.
=> 💄 style: change contrast for codeblocks

config.toml, sass/main.scss, templates/partials/footer.html, templates/partials/nav.html
Allows hosting the page on subdirectories (e.g. `https://example.com/dir`)
=> 🐛 fix: allow for relative paths everywhere

sass/main.scss
=> 🐛 fix: ensure text remains visible during webfont load

templates/macros/macros.html, templates/shortcodes/invertable_image.html
Useful when hosting on a subdirectory. Replaces $BASE_URL by the base_url set in config.toml.
=> ✨ feat: allow relative paths in images

sass/main.scss
It washes out the contrast a bit, but a pure white background on a picture, which matches the background of the light theme, will now perfectly match the dark theme background.
=> 💄 style: don't fully invert images in dark theme

sass/main.scss, sass/parts/_header.scss, sass/parts/_misc.scss, templates/macros/macros.html
- Links in paragraphs are no longer underlined, but rather coloured with the accent-colour of the theme.
- The meta section on posts (date, time to read, tags) is rehauled. It's more compact, less distracting and more minimal.
- Line height is increased.
=> 💄 style: coloured links in paragraph; meta changes

config.toml, templates/macros/macros.html
If the `date_format` variable in `config.toml` is empty, the new format date will be used.
Example of default date format: 2nd August 2043.
=> ✨ feat: use ordinal day number in dates

sass/parts/_header.scss
Both title and navs take up 100% of the width on small displays.
Closes #48
=> 💄 style: improve header's responsiveness

config.toml, content/blog/comments.ca.md, content/blog/comments.es.md, content/blog/comments.md, sass/main.scss, sass/parts/_misc.scss, templates/macros/add_comments.html, templates/macros/content.html
Shows quick navigations on the bottom right of the screen to (1) go to the top of the page or (2) go to the comments (only shown if they're enabled).
Doesn't require JavaScript.
Can be enabled globally (in `config.toml`) or for single posts (in the post matter's `[extra]` section) by setting `quick_navigation_buttons = true`.
This PR also darkens the background of inline code (dark theme only) and simplifies the comment system logic.
=> ✨ feat: add quick navigation buttons

config.toml, static/feed_style/ca.xsl, static/feed_style/en.xsl, static/feed_style/es.xsl, templates/atom.xml, templates/partials/nav.html
Feeds in other language seemed broken, and I changed 'nav.html' to fix issues when the length of language code is not 2.
This is my first PR, warn me if I did anything wrong.
=> fix: multilingual issues in feeds and 'nav.html'

content/blog/shortcodes.ca.md, content/blog/shortcodes.es.md, content/blog/shortcodes.md, sass/main.scss, sass/parts/_image-hover.scss, sass/parts/_image-toggler.scss, templates/shortcodes/image_hover.html, templates/shortcodes/image_toggler.html
- **`image_hover` Shortcode**: This shortcode provides an interactive experience for users by changing the image when hovered over.
- **`image_toggler` Shortcode**: A user-interactive shortcode that swaps between two images when clicked.
=> ✨ feat: Add `image_hover` and `image_toggler` interactive image shortcodes

content/blog/shortcodes.ca.md, content/blog/shortcodes.es.md, content/blog/shortcodes.md, sass/main.scss, templates/shortcodes/wide_container.html
This PR introduces a new `wide_container` shortcode.
It's designed to enhance the content viewing experience across both desktop and mobile platforms. 
On desktops, the shortcode allows for a wider display (such as tables, paragraphs, or code blocks) equivalent to the width of the header. On mobile, the shortcode doesn't alter the display except for tables; they receive a horizontal scroll for better usability.
- Introduce a `wide_container` shortcode in the theme.
- Updated theme documentation to include instructions and usage examples for the new shortcode.
=> ✨ feat: add wide container shortcode

config.toml, templates/base.html, templates/macros/content.html, templates/macros/create_history_url.html, theme.toml
<details>
<summary>TL;DR</summary>
- Add  a "See changes" link to the commit history of updated articles.
- Works with GitHub, GitLab, and Gitea.
- See screenshot below.
</details>
- Introduces a feature for sites hosted on GitHub, GitLab, or Gitea, that automatically attaches a "See changes" link to the commit history of an article right next to its 'last updated' date. This facilitates direct access to version history for updated articles.
- Provides seamless integration with popular Git platforms: GitHub, GitLab, and Gitea.
- Supports auto-detection of the Git platform based on the repository URL. For manual specification, the Git platform can be set in the TOML configuration.
- Introduces a new Tera macro, `create_history_url`, to generate the commit history URLs based on each …
=> ✨ feat: add link to commit history on updated articles

README.md, config.toml, templates/macros/content.html, templates/partials/footer.html
<details>
Enhanced the remote repository linking with a new feature (`show_remote_source`) and two configuration options (`show_remote_changes`, `show_remote_source`).
</details>
This PR introduces one new feature and two new options to enhance the experience of users and provide better control over the display of remote repository links.
These options are only useful if the `remote_repository_url` is set.
1. **Show remote changes option (`show_remote_changes`)**:
- A new configuration option that determines if a link to the commit history of updated posts should be displayed (expands on 109).
- Defaults to `true`.
2. **Show remote source option (`show_remote_source`)**:
- Another configuration option that decides if a link to the repository of the site …
=> ✨ feat(footer): Add link to remote repository

config.toml, sass/parts/_footer.scss, templates/partials/footer.html, theme.toml
<details>
Add a dynamic and translatable copyright notice for the footer.
</details>
This PR adds a feature that allows users to add a custom copyright notice in the footer of their site.
**Key features**:
1. **Dynamic year insertion**:
- Users can use the `$CURRENT_YEAR` placeholder to automatically have the current year inserted into the copyright notice, eliminating the need to manually update it each year.
2. **Markdown support**:
- Enhanced the notice with Markdown support, letting users easily add links, emphasize text, or make other necessary formatting changes.
3. **Multi-language support**:
- For sites in multiple languages, there's an option to set a translated version of the copyright.
---
1. **TOML configuration**:
- Added `copyright` and …
=> ✨ feat(footer): add configurable copyright notice

content/blog/shortcodes.ca.md, content/blog/shortcodes.es.md, content/blog/shortcodes.md, templates/shortcodes/dimmable_image.html, templates/shortcodes/dual_theme_image.html, templates/shortcodes/full_width_image.html, templates/shortcodes/image_hover.html, templates/shortcodes/image_toggler.html, templates/shortcodes/invertible_image.html
<details>
Enhanced image shortcodes with default lazy loading, optional alt attributes, and cleaner HTML output.
</details>
This PR aims to enhance the UX and performance by introducing lazy loading to all image shortcodes and making the `alt` attributes optional. These changes bring about improved page loading times and give more control to users over image rendering.
- Lazy loading has been added to all image-related shortcodes. This defers the loading of images until they are in the viewport, improving page loading time.
- Enabled by default but can be disabled by setting the `lazy_loading` parameter to `false`.
- The `alt` attribute for images is now optional across all shortcodes. This provides greater flexibility while ensuring that best practices can …
=> ✨feat(image shortcodes): add lazy loading, set optional alt attributes & optimise html

config.toml, templates/partials/header.html, theme.toml
This PR addresses issue #117. It adds a new feature that allows users to specify additional stylesheets in the `config.toml` and individual page metadata. This functionality adds flexibility for custom themes and individual post styling.
PR #105 removed a simpler (and undocumented) implementation of this feature.
- Implemented dynamic stylesheet loading in the `header.html` template.
- Added `stylesheets` field to `config.toml` and `theme.toml`.
- Updated documentation in the configuration files to guide users on using the new feature.
1. Specify additional stylesheets in `config.toml` under `stylesheets` as an array. For a single file there's no need for an array.
```toml
[extra]
stylesheets = ["extra1.css", "path/extra2.css"]
```
2. For individual pages, add stylesheets to the `[extra]` …
=> ✨feat(config): add dynamic stylesheet loading via config.toml and page Metadata

templates/macros/format_date.html
The short format was never used.
=> Fix bug in date formatting

README.md
I think this closes https://github.com/welpo/tabi/issues/120.
=> README: Add link to table of contents documentation

templates/base.html, templates/macros/cards_pages.html, templates/macros/content.html, templates/macros/rel_attributes.html, templates/partials/footer.html
This PR introduces a new HTML macro to assemble `rel` attributes dynamically based on config values. It also removes all hardcoded `noopener`, `noreferrer`, and `target=_blank` values from the project.
This PR introduces a macro to assemble `rel` attributes dynamically based on config values, eliminating all hardcoded `noopener`, `noreferrer`, and `target=_blank` values.
- Removed hardcoded `noopener`, `noreferrer`, and `target=_blank` from HTML templates.
- Created a macro for assembling `rel` attributes based on config values.
- Sorted imports in `base.html`.
=> ✨ feat(HTML): introduce rel attribute macro and remove hardcoded values

.githooks/pre-commit, theme.toml
This PR sets saner defaults for when settings are missing in a site using tabi but missing certain `config.toml` values.
For example, a missing extra.email in `config.toml` would render the `theme.toml` value of `mail@example.com`. Certain values like these have been commented out.
Also updates the git pre-commit hook to no longer sync the `[extra]` content of `config` and `theme.toml`, but rather compare the number of lines in each section and abort the commit if they don't match.
Fixes issue #125.
=> 🔧 refactor(theme.toml) set sane defaults

config.toml, templates/macros/content.html, theme.toml
I'm not sure if there is some kind of documentation on all extra fields that exist. I think there really should be. If there is, let me know where, so I can add this one as part of this MR. Or merge it and add it yourself :) Or reject it ofc :)
=> Support hiding the read time indication on pages

config.toml, content/blog/javascript.ca.md, content/blog/javascript.es.md, content/blog/javascript.md, content/blog/markdown.ca.md, content/blog/markdown.es.md, content/blog/markdown.md, templates/base.html, templates/macros/content.html, templates/macros/settings.html, templates/partials/footer.html, theme.toml
<details>
Adds hierarchical setting overrides with priority: page > section > <code>config.toml</code>.
</details>
This PR introduces a new feature that allows for hierarchical overriding of most settings (see list below). The priority of the settings is evaluated as page > section > `config.toml`.
Related issue: #124 
- Adds a new macro (`evaluate_setting_priority`, in `settings.html`) to handle hierarchical setting logic.
- Updates `config.toml` and `theme.toml` to document the new hierarchy logic for each pertinent setting.
- Moved the loading logic for `katex`, `copy_button`, and `footnote_backlinks` from `base.html` to `content.html`.
Here is how the priority is evaluated:
| page | section | `config.toml` | outcome | …
=> ✨ feat(settings): add hierarchy-based setting overrides

static/feed_style.xsl, templates/404.html, templates/archive.html, templates/atom.xml, templates/base.html, templates/macros/add_comments.html, templates/macros/content.html, templates/macros/format_date.html, templates/macros/list_posts.html, templates/macros/paginate.html, templates/macros/set_title.html, templates/macros/table_of_contents.html, templates/macros/translate.html, templates/partials/footer.html, templates/partials/nav.html, templates/shortcodes/multilingual_quote.html, templates/tags/list.html, templates/tags/single.html
<details>
<summary><strong>TL;DR</strong></summary>
Refactored translation logic by using a new `translate.html` macro. 
</details>
This PR overhauls the entire translation code in the templates, replacing a verbose and repetitive `if-else` conditional approach with a more streamlined macro-based solution. 
- Created the `translate.html` macro to handle translation logic.
- Modified all instances of the old `if-else` ([example](https://github.com/welpo/tabi/blob/3344f80539d837df10523160083d91c55b04f58f/templates/partials/nav.html#L14-L19)) translation blocks in Tera templates.
- Centralizes translation logic, making it easier to manage and extend.
- **Readability**: The new macro improves the readability of the templates.
- **Maintainability**: Future translation changes or additions are …
=> ♻️ refactor(translation): streamline translation logic with macro

templates/partials/header.html
Following the install instructions on an empty zola project gives the following error:
```
Error: Failed to build the site
Error: Failed to render pager 1
Error: Reason: Failed to render 'index.html' (error happened in 'base.html').
Error: Reason: Variable `config.extra.custom_subset` not found in context while rendering 'partials/header.html'
```
Adding this config option to my `config.toml` fixes it, but the template should be resilient to that option being absent, like it does with other options.
=> 🐛 fix(header): don't fail if custom_subset absent

sass/main.scss, sass/parts/_home-banner.scss, sass/parts/_misc.scss, sass/parts/_posts_list.scss, templates/macros/cards_pages.html, templates/macros/content.html, templates/macros/list_posts.html, templates/macros/page_desc.html, templates/macros/page_header.html
This PR addresses issue #133, aiming to improve accessibility by introducing `<h1>` tags in key sections.
- Converted `.article-title` from `<div>` to `<h1>`.
- Used `<h1>` tags for `.section-title` and `#home-banner-header`.
- Changed individual project names to use `<h2>` tags.
- Modified blog listing post titles to use `<h2>` tags.
- Updated CSS styling to keep the styling the same.
The use of `<h1>` tags is a standard practice for enhancing web accessibility. These changes align the project with best practices and make the content more accessible to screen readers and other assistive technologies.
=> ♿️ feat(a11y): update heading tags

config.toml, templates/macros/set_title.html, theme.toml
This PR introduces a new configuration option `invert_title_order` that allows users to customize the order of the "site title" and "page title" in browser tabs.
Resolves #135.
- Added `invert_title_order` boolean setting to `config.toml` and `theme.toml`.
- Modified `set_title.html` macro to incorporate the new `invert_title_order` setting.
- Updated `config.toml` and `theme.toml` documentation to explain the new feature.
With longer site titles, the page title can sometimes be obscured when viewed in the browser tab. The new `invert_title_order` setting provides users with more flexibility by allowing the page title to be displayed before the site title. This improves the user experience by making the current page content more prominent when browsing between tabs.
The default title is …
=> ✨ feat(title): add `invert_title_order` config option

config.toml, templates/partials/header.html, theme.toml
This PR introduces a new configuration option, `browser_theme_color`, to set the browser's theme colour (see the [Mozilla Documentation on theme-color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color)).
This option is flexible, allowing for either a single colour value or an array for light and dark modes.
Resolves #137.
- Added a `browser_theme_color` option in `config.toml` and `theme.toml`.
- Implemented logic in Tera template to handle both single colour and array values.
- **Single Value**: Set a single colour that will be used universally across all browser modes.
```toml
browser_theme_color = "#ffffff"
```
- **Array Value**: Use an array to specify different colours for light and dark modes.
```toml
browser_theme_color = ["#ffffff", "#000000"]  # …
```
=> ✨ feat: add `browser_theme_color` config option

templates/partials/header.html
<details>
Live reload now works without conflicting with the existing Content Security Policy.
</details>
This PR addresses issue #139, which reported that the live reload feature was not functioning due to the existing Content Security Policy (CSP) settings.
Modified the `header.html` template to conditionally add `ws:` to the `connect-src` directive in the Content Security Policy. This is done only when Zola is running in serve mode, ensuring that the security policy remains strict in production.
This change is backward-compatible and does not affect existing configurations or features, including comment systems like Hyvor Talk and Isso.
=> 🐛 fix: allow live reload when zola is in `serve` mode

sass/main.scss, templates/internal/alias.html
This PR adds basic styling to the alias / redirect page.
The `main.css` file will be loaded. The current style shows a larger text, fully centered on page, showing the redirection.
The `alias.html` template can't read the config, so custom CSS or skins won't be loaded. It's also impossible to add multilanguage support because of this.
Resolves #149.
=> ✨ feat(alias): style redirect page

templates/partials/multilingual_tags.html
This PR aims to resolves #158, the build-stopping bug when pages are missing translations for all config languages.
1. Modified the Tera template to conditionally check for the existence of translated pages or sections before invoking `get_page` or `get_section`.
2. Utilised `load_data` with `required=false` as a workaround to check for the existence of a `.md` file, thus preventing build errors.
```tera
{# Check if the translated page or section exists #}
{%- set translation_exists = load_data(path=translated_filename, required=false) -%}
{# Get the page or section details #}
{%- if translation_exists -%}
{%- if page.relative_path -%}
{%- set translated_page = get_page(path=translated_filename, metadata_only=true) -%}
{%- else -%}
{%- set translated_page = …
```
=> 🐛 fix(header): check if translations exist while building tags

templates/partials/header.html
This PR adds the ability to specify relative paths for the `social_media_card` in a post. Useful for co-located assets in posts with a structure like:
```
/content/
blog/
post-folder/
index.md
social-media-card.jpg
_index.md
```
In the example above, the social media card can now be set with `social_media_card = social-media-card.jpg` instead of its full path.
- Support for relative paths for `social_media_card` based on the colocated folder.
- Detailed error messages to aid debugging when the image is not found.
- Manually tested the changes by creating posts with relative and absolute paths for the social media cards.
- Verified that appropriate error messages are shown when the image file does not exist at either of the specified paths.
This feature was requested in Issue #161.
=> ✨ feat(social-media-cards): allow colocated paths

config.toml, templates/atom.xml, theme.toml
This PR adds the ability to include the entire `page.content` in `atom.xml` if the optional `full_content_in_feed` is set to `true`.
Resolves #160.
- Modified `atom.xml` Tera template to conditionally include `<content>` tag based on `config.extra.full_content_in_feed` flag.
- Added documentation in the form of comments for this new feature.
Enable `full_content_in_feed` in your site's configuration and observe `atom.xml` through an RSS reader. It should display the full content of the page.
=> ✨ feat(atom): add `full_content_in_feed` option

templates/atom.xml
This fixes broken atom feed which shows the following when there is `<br>` tag on one of the blog:
This makes summary and content tag be able to coexist.
This removes the `| safe` filter on <content> in `atom.xml`.
This puts the summary tag in a separate if statement from the content tag.
=> 🐛 fix(atom): remove safe filter on page.content, and don't make content and summary mutually exclusive

templates/partials/extra_features.html, templates/partials/nav.html
Noticed a self-closing `a` tag and grepped the source for other unnecessary self-closing tags.
=> 🐛 fix(html): Remove unused self-closing tags

templates/partials/header.html
It [hasn't been necessary](https://stackoverflow.com/questions/26346917/why-use-x-ua-compatible-ie-edge-anymore) for a number of years now and the [JavaScript files](https://github.com/welpo/tabi/blob/93eaaea76c01ba18b05113778d11131bec0d3b92/static/js/copyCodeToClipboard.js#L28) target [modern browsers](https://caniuse.com/mdn-javascript_operators_nullish_coalescing) anyway.
=> ♻️ refactor(HTML): remove X-UA-Compatible

config.toml, content/blog/mastering-tabi-settings.ca.md, content/blog/mastering-tabi-settings.es.md, content/blog/mastering-tabi-settings.md, content/blog/security.ca.md, content/blog/security.es.md, content/blog/security.md, templates/partials/analytics.html, templates/partials/content_security_policy.html, templates/partials/header.html, theme.toml
This PR adds support for three privacy-preserving analytics services:
- Plausible
- Umami
- Goatcounter
These are set up in the new `[extra.analytics]`, like so:
```toml
[extra.analytics]
service = "umami"
id = "yourID"
self_hosted_url = ""
```
Docs (Mastering tabi post + `config` and `theme.toml`) have been updated to reflect the new feature.
Only non-self-hosted setups have been tested.
This feature was inspired and discussed in Issue #172.
=> ✨feat: support privacy-respecting analytics

templates/partials/analytics.html
without explicitly defining `https://` it will default to using http instead
=> 🐛 fix(analytics): make goatcounter use https

templates/cards.html
This PR lets users add optional content to cards pages, useful to write a short description about a given page.
=> ✨ feat: add content support to cards template

sass/parts/_quick_navigation_buttons.scss
Fixes an issue where the table of contents popup would overflow with long headings and small viewports.
=> 💄 fix(style): limit width of .toc-container

static/feed_style.xsl
Fixes #206 by applying the new `bloglist-meta` label (and ul/li structure) —introduced in #203— to the stylised feed's date.
=> 🐛 fix(stylised-feed): set proper date class

sass/main.scss, sass/parts/_misc.scss
Fixes an issue where section titles with multiple lines would be very close to each other. Other values are changed so single-line spacing is roughly the same.
=> 💄 fix(style): add line-height to .section-title

config.toml, templates/partials/comments.html, theme.toml
This PR aims to address the issue of malformed URLs in the email notifications generated by Isso, as detailed in #210.
- Modified the Tera template to change how `data-isso-id` and `data-title` are set.
The previous setup used the page's slug to populate `data-isso-id` and `data-title`. This resulted in URLs lacking a separating slash between the domain and the identifier/post in the email notifications.
The new setup uses `default_lang_url` in Tera templates to populate these attributes:
```tera
{%- set default_lang_url = current_path | replace(from='/' ~ lang ~ '/', to = '/') -%}
data-isso-id="{{ default_lang_url }}"
data-title="{{ default_lang_url }}"
{% endif %}
```
While this solution is effective for most use-cases, it's not perfect. Specifically, if a post does not exist in a …
=> 🐛 fix(comments): fix malformed URLs in Isso mails

templates/404.html
Adding a line break between error statement and proposed solution improves readability without reducing accessibility or responsiveness (or at least, I hope so).
Before:
After:
=> feat(404): Split error statement from solution

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/page.html
This pull request adds the ability to override global settings for comment systems at the page-level. Additionally, it refactors the existing code to make it more concise and maintainable.
- **Page-specific overrides**: Adds the capability to disable comment systems on individual pages, overriding global settings. Useful for non-articles like "about", "privacy policy", etc. For example, if you have isso enabled globally, you can disable it for a specific page with `isso = false`.
- **Code refactoring**: Simplifies the existing logic by using loops and making the code more DRY (Don't Repeat Yourself).
- **Documentation**: This feature is documented in the [Mastering tabi](https://welpo.github.io/tabi/blog/mastering-tabi-settings/) post.
The Tera template code for enabling comment systems …
=> ✨ feat(comments): allow page override of global system

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/footer.html, theme.toml
This PR aimed to fix the bug footer url redirect when user add in footer a link external. In the past the external redirection behaviored like the internal now the redirect was fixed to expected behavior.
[212](https://github.com/welpo/tabi/issues/212)
I had to change the footer html adding some conditions to verifiy if the url cotained the prefix http or https and decorate the variable url with get_url if it is not contained in string.
OBS: How the changes is transparent to user, it was not necessary modify documentation.
---
=> 🐛 fix(footer): fix external link redirection in footer

config.toml, content/pages/privacy/index.ca.md, content/pages/privacy/index.es.md, content/pages/privacy/index.md, i18n/ca.toml, i18n/de.toml, i18n/en.toml, i18n/es.toml, i18n/fr.toml, i18n/hi.toml, i18n/it.toml, i18n/ja.toml, i18n/ko.toml, i18n/pt-PT.toml, i18n/ru.toml, i18n/uk.toml, i18n/zh-Hans.toml, i18n/zh-Hant.toml
I'm making two important updates to the tabi demo site with the aim to improve the project while maintaining transparency and respecting user privacy.
To better understand how users interact with the demo site, I'm implementing GoatCounter, an open-source and privacy-friendly analytics tool. The data collected will be non-identifiable and solely aimed at providing insights for improving user experience.
- **Self-Hosted GoatCounter analytics**.
- **Public Dashboard**: I'm introducing a public dashboard, accessible [here](https://tabi-stats.osc.garden/), to share the same insights with the community. In other words: all data collected is 100% public.
I'm also introducing a new Privacy Policy, explaining how the data is collected (for analytics and comments).
The privacy policy has been …
=> 📈 chore(demo-site): add analytics and privacy policy

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/copyright.html, templates/partials/footer.html, theme.toml
As copyright is part of config, it is easier to manage its translations at the same place.
`config.extra.translate_copyright` is still used to declare translation intent for backward compatibility.
It allows to raise an error at build time if someone forgot to move from using i18n files as previously required to the config.toml.
In addition, `$TITLE` is now replaced by the website's title in the copyright.
=> Set copyright translations outside toml files + enhance $VARs

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, templates/shortcodes/dimmable_image.html, templates/shortcodes/dual_theme_image.html, templates/shortcodes/full_width_image.html, templates/shortcodes/image_hover.html, templates/shortcodes/image_toggler.html, templates/shortcodes/invertible_image.html
This PR updates all image shortcodes to support relative paths.
All image shortcodes within the theme have been modified to first attempt to locate images using a relative path. If the image is not found, the shortcode then defaults to the specified absolute path.
Before, for co-located assets, this was necessary (e.g. for a post in blog/shortcodes/index.md):
```
{{ invertible_image(src="blog/shortcodes/img/graph.webp", alt="Invertible graph") }}
```
Now, it's possible to use the same format of relative path that you'd use for a normal image:
```
{{ invertible_image(src="img/graph.webp", alt="Invertible graph") }}
```
No specific accessibility changes were made in this PR, as the updates primarily concern backend image path handling. The front-end display and accessibility of images …
=> ✨ feat: allow relative paths for image shortcodes

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, content/pages/_index.ca.md, content/pages/_index.es.md, content/pages/_index.md, templates/atom.xml
This PR adds a variable `hide_from_feed` to hide pages and sections from the atom feed. This setting follows the hierarchy (see [docs](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy)).
This is useful to hide content like an "about" page, the privacy policy…
---
=> ✨ feat(feed): support hiding pages or sections

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/tags/list.html, theme.toml
Adds an option to display tags in the All Tags page in a more compact way.
By default, the [tags page](/tags) displays tags as:
[TagName](#) — n post[s]
Setting `compact_tags = true` will display them as:
[TagName](#) <sup>n</sup>
Implements #230.
The smaller superscript is slightly less accessible. This is why:
- It's an optional setting;
- The `aria-label` indicates screen readers should read aloud "tag name n posts" (not just "tag name n");
- It's not part of the link, increasing text-background contrast.
Default, `compact_tags = false`:
`compact_tags = true`:
---
=> ✨ feat(tags): add `compact_tags` option

sass/parts/_tags.scss, templates/tags/list.html
This PR introduces a dynamic column layout for the tag list. Depending on the number of tags, the tag list will adjust to display in one (up to 8 tags), two (up to 16), or three columns (17 tags and beyond).
Closes #230.
- Implemented SCSS mixins for column count adjustments.
- Updated the Tera template to apply different classes based on the number of tags (`two-columns` and `three-columns`), defaulting to a single column layout.
- Added responsive design features with media queries in SCSS to adjust the number of columns based on screen size, ensuring a single column layout on mobile devices.
Should not affect accessibility.
See this short video showcasing the dynamic changes to column count, going from 3 to 1 on mobile width:
https://github.com/welpo/tabi/assets/6399341/9f71d010-3ca4-4b …
=> ✨ feat(tags): dynamically adjust tag list columns based on tag count

templates/taxonomy_list.html, templates/taxonomy_single.html
This PR adds fallback/default templates for taxonomies other than tags.
Resolves #229.
The changes include the addition of two new fallback templates:
- `taxonomy_list.html`.
- `taxonomy_single.html`.
Docs: https://www.getzola.org/documentation/templates/taxonomies/
Useful for users who might need taxonomies other than the default, tags.
The taxonomy terms can be translated if the user adds the necessary lines in their `i18n` folder. It falls back to the taxonomy name.
Remains teh same as the default tags page(s).
---
=> ✨ feat: add taxonomy list and single term templates

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/page.html, theme.toml
Allows setting the width of the previous/next article added in #246. 
Navigation feature was added in #246. This configuration feature was requested in #247.
Setting `previous_next_article_links_full_width = false` will make the navigation section for previous/next article matche article width, instead of the full width of the navigation bar at the top. Defaults to `true`.
This setting also follows [the hierarchy](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy).
Unaffected.
`previous_next_article_links_full_width = false`:
---
=> ✨ feat: adjust width of prev/next link section

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/archive.html
This PR introduces the capability to configure a multi-sourced archive page. Previously, the theme only supported archives from a single source (like `blog/`). Now, users can specify multiple sources in their configuration.
Resolves #245.
Modified the Tera template for archives to accept either a single source path or an array of source paths. In the archive page, users can configure:
- **For a single source path**: Set `section_path = "your-path/"` to list posts from a specific directory. Make sure to include the trailing slash.
- **For multiple source paths**: If you want to aggregate posts from various directories, `section_path` can be specified as a list of paths. For example:
```toml
[extra]
section_path = ["blog/", "notes/", "path-three/"]
```
No changes.
---
=> ✨ feat(archive): allow multiple sources in Archive

templates/partials/home_banner.html
Removes support for converting `$BASE_URL` in the main page header (`header.img`) to config's `base_url`.
Users should instead use the actual image path for the `header.img` variable.
Deprecation mentioned in #123.
=> 💥 deprecate(home-banner)!: force proper header.img path

templates/partials/copyright.html
Removes support for translating copyright strings through i18n toml files.
Users should configure the corresponding translation in `copyright_translations.{language_code}` for each language they want to support, as [explained in the docs](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#copyright). Example:
```toml
copyright_translations.es = "© $CURRENT_YEAR $AUTHOR $SEPARATOR A menos que se indique lo contrario, el contenido de esta web está disponible bajo la licencia [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
```
Discussed in #214 and added the new translation feature in #215.
=> 💥 deprecate(i18n)!: force config.toml copyright translation

templates/base.html
Add support for RTL languages, such as Arabic and Hebrew, by adding the `dir` attribute to the `body` tag if the language is RTL.
I added the `extra.rtl` and `extra.lang_rtl.<lang>` to the config, with this change, we can specify the languages that are RTL and the `dir` attribute will be added to the `body` tag.
=> ✨ feat(i18n): add Right-to-left script support

i18n/ar.toml
Please don't merge the PR until someone speaks Arabic review it
=> 🌐 feat(i18n): add Arabic language

static/feed_style.xsl
Fix https://github.com/welpo/tabi/issues/267
The page will looks like this after this PR
> [!NOTE]
> I change the language from English to Arabic, to see the page in `LTR` and `RTL`
https://github.com/welpo/tabi/assets/59842932/a7575de0-fa67-4c09-aa1d-b4fae813a759
=> 🐛 fix(i18n): atom feed page direction for RTL langs

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, templates/shortcodes/dimmable_image.html, templates/shortcodes/dual_theme_image.html, templates/shortcodes/full_width_image.html, templates/shortcodes/image_hover.html, templates/shortcodes/image_toggler.html, templates/shortcodes/invertible_image.html
Modifies all image shortcodes to allow remote sources. Before, using a link would prefix it with the `base_url`.
- Added checks to differentiate between remote URLs and local image paths.
- Ensured all changes are backward compatible, maintaining existing functionality while introducing these improvements.
---
=> ✨ feat(shortcodes): support URLs for image source

templates/partials/multilingual_tags.html
Fix Zola build error when marking the translations of the page as drafts
https://github.com/welpo/tabi/issues/281
Get translations of the current page by using builtin `section.translations` or `page.translations`
N/A
N/A
---
=> 🐛 fix(templates): "multilingual_tags" error on drafts

static/feed_style.xsl
We've observed an inconsistent behavior in the generation of Atom feed links, specifically regarding the construction of the `href` attribute for the `visit_the_site` link. The issue arises depending on the `skin` variable's value in the `config.toml` file. When the `skin` variable is not set (i.e., left as an empty string ""), the XPath expression `/atom:feed/atom:link[2]/@href` successfully retrieves the intended URL stored in `config.base_url`. However, when the `skin` variable is initialized with a value (e.g., "red"), the mentioned XPath expression fails to function as intended, leading to incorrect `href` values in the generated Atom feed.
This behavior suggests that the insertion of an additional `<link>` element related to the skin configuration alters the document structure, …
=> 🐛 fix(feed): fix "Visit website" link with skin config

templates/partials/content_security_policy.html
- Added Umami's API gateway domains to the automatic Content Security Policy generation.
closes #299 
They should be live at https://www.richtman.au now and one can see the `Config.toml` [here](https://github.com/arichtman/www.richtman.au/blob/65459a76bb02c7dd6e05a0e64d82c2c2fcb36ba1/config.toml#L89)
No impact to accessibility.
No visual impact.
---
=> 🐛 fix(CSP): add Umami API URLs to CSP

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/page.html, theme.toml
Adds `show_date` option to display/hide the date on pages. It follows [the hierarchy](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy).
Besides adding the option, this PR also adds logic to conditionally show the $SEPARATOR in the metadata. This avoids situations where the first element shown is the separator (e.g. hiding the date but showing reading time).
Resolves #302.
---
=> ✨ feat: add option to display/hide date in metadata

templates/partials/content_security_policy.html
Umami changed their callback DNS again.
If there's a way to blanket allow `umami.dev` that'd be nice.
Closes #309
CSP template but only if using Umami
=> 🐛 fix(analytics): allow Umami through CSP

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, sass/parts/_image-hover.scss, sass/parts/_image.scss, templates/shortcodes/dimmable_image.html, templates/shortcodes/dual_theme_image.html, templates/shortcodes/image_hover.html, templates/shortcodes/image_toggler.html, templates/shortcodes/invertible_image.html
Adds an `inline` option to all image shortcodes (except the `full_width` one, for obvious reasons). When set to `true`, the image(s) will be displayed inline with the text. The images will be vertically aligned with the text.
Idea from #314.
No changes; tested with VoiceOver.
---
=> ✨ feat(shortcodes): add `inline` option to image shortcodes

templates/partials/main_page_posts_list.html, templates/section.html
Added the possibility of hiding posts on the main page.
To achieve this, do not set `paginate_by` nor `section_path` in the `[extra]` section of an `_index.md` file.
Resolves #316.
- Added conditional logic to determine the order of displaying sections (projects or posts) on the main page.
- Updated the `<main>` tag to conditionally apply the appropriate CSS class based on the presence of sections.
- Included dynamic construction of template paths and used them for conditional inclusion of sections.
No changes.
---
=> ✨ feat(homepage): allow hiding posts listing

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, i18n/ar.toml, i18n/ca.toml, i18n/de.toml, i18n/en.toml, i18n/es.toml, i18n/fa.toml, i18n/fr.toml, i18n/hi.toml, i18n/it.toml, i18n/ja.toml, i18n/ko.toml, i18n/nl.toml, i18n/pt-PT.toml, i18n/ru.toml, i18n/uk.toml, i18n/zh-Hans.toml, i18n/zh-Hant.toml, templates/macros/format_date.html, templates/page.html, theme.toml
Adds `show_author` configuration option. This will display the authors set on `authors = []` in the front matter of the post. If this is not available, it will fall back to `author = ""`in `config.toml`.
Resolves #319.
- update `page.html` to render the author(s) in the metadata
- i18n files updated with new strings to list authors
- `format_date.html` updated to ensure consistent spacing
Uses semantic HTML.
---
=> ✨ feat: add option to show author in post metadata

templates/macros/settings.html
By requesting only the metadata in `get_section` this speeds up my build by a massive amount.
See #324
=> ⚡️ perf: getting the metadata only in this common operation speeds up my build 10 times

config.toml, content/_index.ca.md, content/_index.es.md, content/_index.md, content/blog/_index.ca.md, content/blog/_index.es.md, content/blog/_index.md, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/footer.html, theme.toml
Updates the footer template to work with Zola 0.19.0. Note: if you are using two feeds, only the first one from `feed_filenames` will be linked on the footer.
Fixes #335 
---
=> 🐛 fix(footer): show feed icon on Zola 0.19.0

i18n/ar.toml, i18n/ca.toml, i18n/de.toml, i18n/en.toml, i18n/es.toml, i18n/fa.toml, i18n/fr.toml, i18n/hi.toml, i18n/it.toml, i18n/ja.toml, i18n/ko.toml, i18n/nl.toml, i18n/pt-PT.toml, i18n/ru.toml, i18n/uk.toml, i18n/zh-Hans.toml, i18n/zh-Hant.toml, templates/page.html
Changes the `last_updated_on` i18n string to (1) include a `$DATE` placeholder and (2) be less verbose.
The placeholder is useful for languages like Japanese. Before, all languages were forced to the `last_updated_on string` + `$date` structure. The new format improves translation accuracy.
Idea from #330.
- Update i18n strings
- Implement `$DATE` placeholder replacement
Remains the same.
---
=> 🌐 refactor: improve last_updated_on format

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/tags/list.html, templates/taxonomy_list.html, theme.toml
Adds new variable `tag_sorting` with two options: `name` (default) and `frequency` (new).
Implements feature request: #341 
---
=> feat: optional alternative tags sort order based on posts count

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, sass/main.scss, sass/parts/_posts_list.scss, static/feed_style.xsl, templates/atom.xml, templates/macros/list_posts.html, theme.toml
This pull request adds an option to the config.toml to change the displayed dates on the bloglist.
#326
`config.toml`
```toml
bloglist_date = "updated"
```
See the dates on the left side
Option bloglist_date = "updated":
Option bloglist_date = "date":
Option bloglist_date = "both":
---
=> ✨ feat: add date visibility options to post list

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/macros/list_posts.html, theme.toml
Without this fix, there is no date if you set `post_listing_date = "updated"` and the post has no updated date.
#326 
#330 
If the post doesn't has an updated entry, the creation date is used:
---
=> Use post.date when no post.updated entry exists

config.toml, content/blog/customise-tabi/index.ca.md, content/blog/customise-tabi/index.es.md, content/blog/customise-tabi/index.md, sass/main.scss, static/feed_style.xsl, templates/atom.xml, theme.toml
Uses CSS variables to follow user OS settings even with JavaScript off. Now the atom feed preview follows the `default_theme`, defaulting to user OS preference.
Idea from #330.
Updates CSS (adds 2KB), atom feed and feed styling xsl transformation.
No changes.
---
=> ✨ feat: follow user OS theme with JS disabled

templates/partials/header.html
This PR fixes a bug where feed links were being rendered in the header even when feeds were disabled. It introduces a more flexible and robust solution for handling feed links in the header template.
Fixes #352.
- Modified `header.html` to conditionally render feed links
- Added support for multiple feed types (Atom and RSS)
- Improved code to use `config.feed_filenames` for Zola 0.19.x and newer, falling back to `config.feed_filename` for older versions
Unaffected.
---
=> 🐛 fix(header): render feed links based on config

sass/main.scss, sass/parts/_zola-error.scss
This PR introduces minimal CSS styling to enhance the visibility of Zola error messages during development. It centers the error messages both vertically and horizontally on the screen and applies consistent styling using theme variables.
CSS specificity should target only Zola errors and not affect user content.
- Added a new SCSS file `zola-error.scss` to style Zola error messages
- Positioned error messages in the center of the viewport
- Applied theme-consistent colors using existing CSS variables
- Improved readability of error messages
The changes improve the visibility of error messages, which enhances the overall accessibility of the development process. The centered position and improved contrast make the messages easier to notice and read for all users.
Hard to see, at the very …
=> 💄 style(error): enhance visibility of Zola errors

content/blog/faq-languages/index.ca.md, content/blog/faq-languages/index.es.md, content/blog/faq-languages/index.md, i18n/et.toml
Added translation into Estonian
New file `et.toml` and changed tabi's website  'faq-languages' to list Estonian as supprted language.
=> 🌐 feat(i18n): add Estonian language

templates/macros/list_posts.html, templates/page.html, templates/partials/footer.html, templates/partials/nav.html
Adds quotes around expressions in places where they were missing.
Mostly fixed `href` attributes of links, errors which are ignored by web browsers. Also fixed `alt` and `title` attributes of links inside the social navigation block.
This was my initial motivation for doing this, as missing quotes around `alt` and `title` attributes on links inside the social navigation block prevents putting text with spaces.
---
=> Add missing quotes around some expressions

sass/parts/_misc.scss
New blockquote for RTL, where the border and padding in the right
I have tried `:dir(rtl)` syntax but it doesn't work properly, also I tried to use `[dir="rtl"]` only without ltr, but it doesn't work
| Before | After |
| :----: | :---: |
| ![image](https://github.com/user-attachments/assets/8b52e44b-b892-4999-a647-08d5cb820b72)  | ![image](https://github.com/user-attachments/assets/97f23fa1-14d9-455d-b451-d3570b46e4a3) |
---
=> 🐛 fix(rtl): fix blockquote in rtl

sass/main.scss, sass/parts/_home-banner.scss
Reduces the sizes of headers and lists on the main page to align with the sizing of single pages. This avoids overlapping text and too-large lists on the main landing page.
Resolves #374.
- Sets `rem` sizes for headers instead of `em`
- Sets a size of `1rem` for lists in the home banner.
Improved by avoding overlapping header text as well as properly sized list elements.
Before, on small screens or large text setups the header text would overlap when wrapped:
Now, headers and lists have the same size as they would in articles, avoiding overlapping text and too-large lists:
---
=> ♿️ fix: reduce main page header/list sizes

content/blog/customise-tabi/index.ca.md, content/blog/customise-tabi/index.es.md, content/blog/customise-tabi/index.md, sass/parts/_admonitions.scss, sass/parts/_footer.scss, sass/skins/blue.scss, sass/skins/evangelion.scss, sass/skins/indigo_ingot.scss, sass/skins/lavender.scss, sass/skins/lowcontrast_orange.scss, sass/skins/lowcontrast_peach.scss, sass/skins/lowcontrast_pink.scss, sass/skins/mint.scss, sass/skins/monochrome.scss, sass/skins/red.scss, sass/skins/sakura.scss, sass/skins/teal.scss
Ensure dark theme applies when explicitly set or by OS preference. Solves styling inconsistencies.
Resolves #379. Bug introduced in #357. Discussion started in #378.
Consistently applies styling for dark/light mode, regardless of OS theme, default tabi theme, and theme switcher status (enabled/disabled).
Specifically:
- Skins now work properly when OS theme is set to dark.
- Refactored skins and theme variables to use a mixin for consistency.
- Fixes social icons (footer) being the wrong colour when (1) theme switcher was disabled, (2) `default_theme` was unset in `config.toml`, and (3) the OS was set to dark theme.
- Fixes a similar issue with admonition styling (see screenshots).
- Simplifies SCSS for admonitions, making it more maintainable.
The changes improve accessibility by …
=> 🐛 fix: improve dark mode and OS theme handling

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/macros/settings.html, templates/page.html
Fixes the build error for pages nested within pages and implements a new hierarchy system to find the nearest parent page or section for nested pages.
Fixes #384.
- Fix build error for pages nested within pages by checking for `last_ancestors` length
- When a page is within a page, the hierarchy would not find the nearest section. This PR implements the logic to find the parent page or nearest section based on the `page.components`. It uses a hack to check if a file (section) exists and manually builds the path to the `_index.md`. In short: it's fragile. It was either this or have the hierarchy not work for nested pages.
- Update docs regarding Hierarchy to mention nested pages behaviour
- Add comprehensive debugging output for future troubleshooting
---
=> 🐛 fix: allow pages within pages

static/feed_style.xsl, templates/atom.xml
Addresses W3C validation warnings for the Atom feed and improves compliance with feed standards. It restructures the custom metadata in the feed and adjusts the XSL transformation accordingly.
Reported in #391.
- Remove custom `post_listing_date` element from main feed structure
- Remove unused `xmlns:base` attribute from `<feed>` element
- Replace `str` namespace with `tabi` and move custom elements to `<tabi:metadata>`
- Add `rel="alternate"` to main site link for clarity
- Adjust XSL transformation to match new feed structure
Probably unchanged. Possibly improved due to better compatibility with feed readers.
---
=> 🐛 fix(feed): resolve Atom feed validation issues

static/feed_style.xsl, templates/atom.xml
Enhances the "Visit website" link in the Atom feed to be section-aware and properly link to the language-specific main page when not in a section or tag.
#393
- Link to language-specific main site (used to always link to `/`)
- If the feed belongs to a tag, it displays it on the link (see screenshot)
- Add section/tag information to the Atom feed template
- Update XSL transformation to conditionally display section/tag
---
=> ✨ feat(feed): make "Visit website" link context-aware

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, templates/shortcodes/remote_text.html
This PR adds support for line range selection in the `remote_text` shortcode. Users can now specify start and end line numbers when embedding text from remote or local files.
Requested in #397.
- Added `start` and `end` parameters to the `remote_text` shortcode
- Updated the shortcode to slice the text content based on these parameters
- Updated documentation to explain the new functionality
- Added examples demonstrating the use of line range selection
---
=> ✨ feat(remote_text shortcode): support relative paths

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/analytics.html, theme.toml
`umami.js` should be `script.js` for self hosting URL.
- self hosting analytics for Umami fixed.
File name changed
---
=> 🐛 [Bugfix] Update analytics.html for self hosting Umami

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md
Mermaid usage was missing in the documentation.
I just added it as for any other shortcode.
Add mermaid usage in documentation
Nothing particular for this change, just reused other similar shortcode usage as base.
---
=> 📝 docs: add mermaid shortcode usage

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/header.html, theme.toml
Add Fediverse author meta tag to header through variable `fediverse_creator`.
#408 
- Added conditional insert of meta tag to header template
Meta-element, should not impact accessibility?
Live at https://www.richtman.au
---
=> ✨ feat: add fediverse creator metadata support

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, sass/parts/_misc.scss, templates/shortcodes/force_text_direction.html
Introduces a new shortcode `force_text_direction` that allows fine-grained control over text direction within specific content blocks.
Related: #412 and #411
- Introduced new `force_text_direction` shortcode
- The shortcode overrides both the global `force_codeblock_ltr` setting and the document's overall direction
- Accepts "ltr" (left-to-right) or "rtl" (right-to-left) as direction parameter
---
=> ✨ feat: add force_text_direction shortcode

README.md, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/main_page_posts_list.html
Updated documentation to clarify instructions for listing recent posts on the main page, aiming to avoid confusion regarding the use of `paginate_by` and `section_path`. Changes were made to the README and the "Mastering tabi" post.
Adds warning when conflicting settings are set.
The lack of clarity in the docs was evidenced in #417.
- **Documentation:**
- Updated README and "Mastering tabi" post with clearer instructions for listing recent posts.
- Separated setup instructions into two distinct options: root path (`/`) and subdirectory (e.g., `/blog`) configurations.
- **New warning:**
- Implemented a dynamic warning message on the main page for conflicting configurations.
- Warning appears when `paginate_by` is set without posts, but `section_path` contains posts.
- Provides a clear …
=> 📝 docs: clarify instructions for listing recent posts

sass/parts/_header.scss, templates/page.html, templates/partials/nav.html
Improves wrapping of navigation bar icons —grouping them together for wrapping— and post metadata (see screenshots).
- Group wrapped navigation icons
- Make metadata 'separator' unselectable
- Better wrapping of article metadata:
- Tags never get split
- Separator uses a class instead of non-breaking spaces
- Elements are joined with their separator
- Elements starting in a new line (due to wrapping), do not get space before the separator
Improved: adds `aria-hidden="true"` to the separator. This prevents screen readers from announcing decorative content that could be distracting or redundant.
The list structure (`<li>` elements) already provides sufficient context for understanding that these are related but separate pieces of information. Before, the screen reader would announce …
=> 💄 style: improve navigation bar & metadata wrapping

templates/page.html
Fixes a variable name collision that was breaking Isso comments in multilingual sites. The series feature introduced in #406 used a global variable named `current_path` which conflicts with [Zola's built-in variable of the same name](https://www.getzola.org/documentation/templates/overview/), used by the Isso comments implementation.
Fixes #426
- Renamed the series-related variable from `current_path` to `series_path_components` to avoid collision with Zola's built-in variable
- Made the variable name more descriptive of its actual purpose (storing path components for series navigation)
- Grouped comment logic in `page.html`
---
=> 🐛 fix: Isso comments in multilingual setups

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/macros/list_posts.html, templates/partials/main_page_posts_list.html, templates/section.html
Adds support for pinned posts when using pagination (`paginate_by`). Previously, pinned posts only worked when using `section_path`.
Also restricts pinned posts to appear only on root pages (e.g., `/`, `/es/`, `/fr/`).
Should've probably been added in #424.
- Handle pinned posts with pagination
- Show pinned posts only on page 1
- Restricted pinned posts to root pages only (language-aware)
- Added clear documentation about pinned posts behavior with pagination
---
=> ✨ feat: allow pinned post with pagination

sass/main.scss
Added `accent-color` CSS variable to style form elements (checkboxes, radio buttons, range inputs) consistently with the theme's primary color.
Added `accent-color: var(--primary-color);` to the global styles. This affects:
- Checkboxes
- Radio buttons
- Range inputs
- Progress bars
Respects the use of skins or custom CSS.
Before:
Uses the OS accent colour (pink, for me)
After:
Uses the `primary-color` variable.
---
=> 💄 style: set accent color to match theme

sass/main.scss
Added `scrollbar-color` CSS variable to style scrollbars consistently with the theme's primary color. Respects the use of custom CSS / skins.
Same goal as #429: theme cohesion.
Added `scrollbar-color: var(--primary-color) transparent;` to the global styles for custom scrollbar styling that matches the theme.
---
=> 💄 style: colour scrollbar to match primary colour

content/blog/markdown/index.ca.md, content/blog/markdown/index.es.md, content/blog/markdown/index.md, sass/parts/_code.scss
Adds padding for line numbers in code blocks. Reduces their opacity (made it similar to VSCode), and standardises the font size between all code blocks (those with line numbers had a larger font).
Adds numbered code block to Markdown demo.
Fixes #435 (#434)
Before, no spacing, larger font when adding line numbers:
After:
---
=> 💄 style: fix numbered code blocks

sass/parts/_home-banner.scss
Improves home banner balance when displaying shorter intro texts.
Before, setting a brief intro text would center the container and enlarge the image.
Before:
After:
---
=> 💄 style: fix home banner layout for short intro

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, templates/shortcodes/dimmable_image.html, templates/shortcodes/dual_theme_image.html, templates/shortcodes/full_width_image.html, templates/shortcodes/image_hover.html, templates/shortcodes/image_toggler.html, templates/shortcodes/invertible_image.html
Adds `raw_path` to all image shortcodes. If set to `true`, the `src` parameter will be used as is. Useful for colocated assets with a custom slug (see [Zola issue #2598](https://github.com/getzola/zola/issues/2598)).
Resolves #436. Zola issue: https://github.com/getzola/zola/issues/2598
---
=> ✨ feat: add 'raw_path' parameter to image shortcodes

content/blog/shortcodes/index.ca.md, content/blog/shortcodes/index.es.md, content/blog/shortcodes/index.md, sass/main.scss, sass/parts/_aside.scss, templates/shortcodes/aside.html
Adds `aside` shortcode for supplementary content.
Users can set the margin on which to show the note. The content can be provided as a `text` parameter or using body within the shortcode tags (see docs).
Resolves #444
- Adds shortcode
- Updates CSS
- Adds documentation
Uses semantic HTML ([`<aside>`](https://developer.mozilla.org/docs/Web/HTML/Element/aside)) and has good contrast for the mobile look.
Wide screen:
Mobile (or narrow screen):
---
=> ✨ feat(shortcodes): add 'aside' shortcode for side notes

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/info-page.html, templates/partials/extra_features.html
This change makes it possible to use the `info-page.html` template on the root path (`"/"`), which in zola is always a "section" and can't be set to "page".
The related issue(s) is/are actually in zola and not really in tabi. It's a known limitation in zola that the root path has to be a section and can't be a page (see linked issues later). Because of that templates designed for pages typically can't be used for sections (and thus not as a root path "/" landing page).
Thankfully in tabi a lot of things are already pretty agnostic between sections and pages, so it only needed some minor tweaks to make the template work at the root level.
As said before, not really a tabi issue, but here are related zola issues and discussions:
- https://github.com/getzola/zola/issues/2334
- …
=> ✨ feat: support using info-page.html for sections

config.toml, content/blog/custom-font-subset/index.ca.md, content/blog/custom-font-subset/index.es.md, content/blog/custom-font-subset/index.md, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/header.html, theme.toml
I've created my own custom skin, that doens't use custom font, so I added a way to disable the font-subset.
- Added setting for `enable_subset`, which is set to true by defaults
- Amended logic in `header.html` to check if the subset is enabled
- Updated mastering-tabi-settings blogpost (English version)
---
=> ✨ feat: support disabling of the font-subset in header

templates/partials/header.html
Setting `nofollow` to all pages is bad practise, it hurts crawlability. This causes significant issues with, for example, SEO. 
Setting `index` is the default, so no need to implicitly set it.
---
=> 🐛 fix: remove `nofollow` robots meta tag

static/feed_style.xsl
Fixes CSS loading in subfolder installations by deriving the base path from the feed URL instead of relying on xml:base. Uses same logic as sitemap styling.
N/A
Before:
After:
---
=> 🐛 fix(feed): load CSS in subfolder setups

templates/partials/header.html
Move the Content Security Policy partial to be included closeer to the top of `<head>` in order to protect additional resources.
None
Per the [CSP spec on delivering Content Security Policy using the meta element](https://www.w3.org/TR/CSP/#meta-element):
> Authors are strongly encouraged to place meta elements as early in the document as possible, because policies in meta elements are not  applied to content which precedes them. In particular, note that resources fetched or prefetched using the Link HTTP response header field, and resources fetched or prefetched using link and script elements which precede a meta-delivered policy will not be blocked.
---
=> 🔒️ fix(header): reposition include of CSP partial

README.md
I propose to add my personal website (idle-ti.me) to the list of sites using tabi.
N/A
In the README.md file, I added a line to the table that lists the sites that use tabi (no other changes).
N/A
N/A
---
=> 📝 misc(README): add idle-ti.me blog to sites using tabi

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/nav.html
Fix navigation menu handling of external URLs and update documentation to clarify external URL support.
Fixes #480
This PR fixes a bug where external URLs in the navigation menu were being treated as relative URLs, resulting in incorrect paths like `http://127.0.0.1:1111/https://example.com/`. The fix:
1. Adds URL type detection to check if URLs start with "http"
2. Handles external URLs directly without using `get_url()`
3. Updates documentation to clarify external URL support and usage
This implements the same fix that was previously applied to the footer menu (#212).
---
=> 🐛 fix: support external URLs in menu

sass/parts/_header.scss, templates/partials/nav.html
Fix accessibility issue in the navigation menu where list items were incorrectly nested inside a div within an unordered list, causing Lighthouse warnings and semantic HTML violations.
Fixes #477
This PR improves the navbar's HTML semantics while maintaining its visual appearance and functionality.
- Fixed Lighthouse warning about improper list nesting
- Improved semantic structure for better screen reader compatibility
---
=> ♿️ fix: improve menu accessibility

content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/archive.html
> [!WARNING]
> Archive now enforces a `date`-based ordering. It used to respect the archived sections `order_by` value.
Enforces chronological sorting in the archive template and adds a configurable sort direction via `archive_reverse`. This change ensures consistent date-based ordering across all archive posts, regardless of their source sections' sorting configurations.
Since an archive is (1) inherently date-related, and (2) only post dates (not update dates) are shown, I believe this (breaking) change makes sense. Do let me know if you think otherwise.
> [!NOTE]
> Would you like the archive to support different sorting options for your site? [Open a feature request](https://github.com/welpo/tabi/issues/new?template=3_feature_request.yml) and let me know!
- Enforces publication date …
=> 💥 feat(archive)!: enforce chronological sorting

templates/archive.html, templates/page.html, templates/partials/cards_pages.html
I added `safe` and `markdown` filters to some pages because I couldn't use Markdown and HTML formatting in titles and descriptions (like _italic_ or `<em>italic</em>`) - they was rendering "as-is" and not interpreted as I wanted to see them.
This PR resolves issue #468 
---
=> ✨ feat: render markdown in page titles & descriptions

sass/parts/_misc.scss
This PR fixes the external link icon breaking word wrapping on long link text. Previously, links with the external icon would be treated as a single unbreakable unit, causing awkward line breaks.
Fixes #495
The root cause was the `display: inline-block` property applied to external links. This change:
- Removes the `display: inline-block` property from external links
- Adjusts the icon implementation to use `inline-block` only on the pseudo-element
Unaffected/improved.
---
=> 💄 fix: fix external link icon breaking word wrapping

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/hcard.html, templates/section.html, theme.toml
This adds a minimal hidden h-card to the home page.
Discussed in #463
The `templates\section.html` template includes a new partial `partials\hcard.html` which contains the h-card content.
The h-card stays hidden, so I kept the html minimal and I did not include any new css.
There is a new `[extra.hcard]` section at the end of the `theme.toml` and `config.toml` files.
I added a _Indieweb / Representative h-card_ paragraph at the end of the _Mastering tabi settings_ page.
---
=> ✨ feat(indieweb): add hidden h-card

templates/partials/hcard.html
This fixes missing  html closing tags in hcard template 
#507
In partials/hcard.html:
- Add closing div tag
- replace `set` by `set_global` in for loop
- [x ] Bug fix (fixes an issue without altering functionality)
---
=> 🐛 fix: fix hcard html tags

templates/page.html, templates/partials/hcard.html, templates/partials/hcard_small.html
Add a small hcard to each post in order to add author name, avatar and homepage links when doing webmentions from articles. This is different from the  main  hcard of the homepage which has more information and is used for profile, but is not automatically fetched by webmentions parsers if the webmention link to another page 
#463
- add the partial  `partials\hcard_small.html`
- include this partial in the page template `templates/page.html` if the `config.extra.hcard` is set and `config.extra.hcard.enable` is true. 
---
=> ✨ feat(webmentions): use small hcard in post page

config.toml, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/partials/analytics.html, theme.toml
Adds support for an optional `do_not_track = true` setting under `[extra.analytics]` to control whether Umami respects the browser’s Do Not Track (DNT) header.
This change makes the behavior configurable and consistent with other analytics services, which typically do not default to honoring DNT.
Closes #535 
- Added conditional output of `data-do-not-track="true"` in the Umami script tag
- Introduced `do_not_track` option in `[extra.analytics]` in `config.toml`
- Updated `theme.toml` with a representative key and example
- Documented the new setting in the English version of the "Analytics" configuration page
Only the English documentation has been updated due to my language limitations.
Not applicable. This change does not affect the frontend UI or accessibility.
Not applicable.
---
=> ✨ feat(analytics): make Umami DNT behavior configurable

templates/partials/nav.html
Provide a trailing slash on the home navigation link to work if the `base_url` is set to a `/` only because in this case the home-link does not work.
#546
use the additional parameter `trailing_slash` from the `get_url` function
=> ♻️ refactor: force a trailing slash on the nav home title

templates/partials/content_security_policy.html
This corrects the CSP header as to not escape the HTML. When using Tera `join`, the original resulted in the following (on a fresh tabi install with no optional features enabled):
```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self';font-src &#x27;self&#x27; data:;img-src &#x27;self&#x27; https:&#x2F;&#x2F;* data:;media-src &#x27;self&#x27;;style-src &#x27;self&#x27;;frame-src player.vimeo.com https:&#x2F;&#x2F;www.youtube-nocookie.com;connect-src 'self' ws:;script-src 'self' 'self'">
```
This change corrects the above to be:
```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self';font-src 'self' data:;img-src 'self' https://* data:;media-src 'self';style-src 'self';frame-src player.vimeo.com https://www.youtube-nocookie.com;connect-src …
```
=> ♻️ refactor: prevent HTML escaping of joined CSP strings

config.toml, content/blog/faq-languages/index.ca.md, content/blog/faq-languages/index.es.md, content/blog/faq-languages/index.md, content/blog/mastering-tabi-settings/index.ca.md, content/blog/mastering-tabi-settings/index.es.md, content/blog/mastering-tabi-settings/index.md, templates/archive.html, theme.toml
Implement per-language and universal date formatting for the archive page. The archive date format can be specified universally:
```toml
[extra]
archive_date_format = "%b %-d"
```
And it can also be specified per-language:
```toml
[extra]
date_formats = [
{ lang = "es", long = "%d de %B de %Y", short = "%-d %b %Y", archive = "%d de %b" },
{ lang = "de", long = "%d. %B %Y", short = "%d.%m.%Y", archive = "%d. %b" },
]
```
Further resolves #555 
Added support for a universal and language-specific archive date formats through a new `archive_date_format` configuration option and an extension to the `date_formats` configuration option in `config.toml`. Users can now customize the archive date format (day and month) per language to match local conventions (e.g. American English "Feb 3" vs …
=> ✨ feat: allow custom archive date format
